### ISSUE TITLE
Installation of additional_tags fails with "uninitialized constant Additionals"

### ISSUE THREAD

**Issue by IWilhelmy** [AlphaNodes/additional_tags#13]
Hi!
we are using additionals-plugin (great - thanks for that!) and would like to install additional_tags, but installation fails:

`redmine@ubuntu_test_1804:~/redmine$ !620
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant Additionals
/opt/redmine/redmine-4.1.0/plugins/additional_tags/init.rb:19:in `block in <top (required)>'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:94:in `instance_eval'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:94:in `register'
/opt/redmine/redmine-4.1.0/plugins/additional_tags/init.rb:8:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:181:in `block in load'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:172:in `each'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:172:in `load'
/opt/redmine/redmine-4.1.0/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.1.0/config/environment.rb:16:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)`
bundle exec rake redmine:plugins:migrate RAILS_ENV=production

The Redmine system information is as follows:

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.7
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.23-master

Any suggestions?

thanks!

**Comment by IWilhelmy** [comment]
SOLVED! Updated additionals plugin and installation worked. Thanks!

additionals                    3.0.3-master
