### ISSUE TITLE
Problem uninstalling redmineup_tags after additional_tags is installed

### ISSUE THREAD

**Issue by amacado** [AlphaNodes/additional_tags#24]
Steps to reproduce:
1. Install redmineup_tags plugin as instructed by developers
2. Create some tags (may optional)
3. Follow instructions on additional_tags installation (remove redmineup_tags folder, install additionals, install additional_tags, bundle install and db migrate)
4. Be happy because migration from redmineup_tags has worked 😄 🥳 
5. Try to remove no-longer required tables by executing the uninstall mechanism as [redmine tutorial says](https://www.redmine.org/projects/redmine/wiki/plugins#Uninstalling-a-plugin) (to make this work the redmine_up folder needs to be present in the plugins directory, so we place it there again.
```bundle exec rake redmine:plugins:migrate NAME=redmineup_tags VERSION=0 RAILS_ENV=production```
6. Cry in pain because `additional_tags plugin cannot be used with redmineup_tags plugin.` and uninstall is aborted
7. Follow this issue because you have encountered the same problem 😃  

Full error log:
```
bundle exec rake redmine:plugins:migrate NAME=redmineup_tags VERSION=0 RAILS_ENV=production
Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
/var/www/redmine-testenv/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
/var/www/redmine-testenv/plugins/redmine_agile/init.rb:14: warning: previous definition of FCSV was here
rake aborted!

additional_tags plugin cannot be used with redmineup_tags plugin.
/usr/local/rvm/gems/ruby-2.7.2/gems/redmine_plugin_kit-1.0.2/lib/redmine_plugin_kit/loader.rb:101:in `block in incompatible?'
/usr/local/rvm/gems/ruby-2.7.2/gems/redmine_plugin_kit-1.0.2/lib/redmine_plugin_kit/loader.rb:100:in `each'
/usr/local/rvm/gems/ruby-2.7.2/gems/redmine_plugin_kit-1.0.2/lib/redmine_plugin_kit/loader.rb:100:in `incompatible?'
/var/www/redmine-testenv/plugins/additional_tags/lib/additional_tags.rb:22:in `setup'
/usr/local/rvm/gems/ruby-2.7.2/gems/redmine_plugin_kit-1.0.2/lib/redmine_plugin_kit/plugin_base.rb:14:in `setup!'
/var/www/redmine-testenv/plugins/additional_tags/init.rb:38:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:605:in `catch'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:513:in `each'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/reloader.rb:89:in `prepare!'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
/var/www/redmine-testenv/config/environment.rb:16:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/application.rb:337:in `require_environment!'
/usr/local/rvm/gems/ruby-2.7.2/gems/railties-5.2.5/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.7.2/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

Is there any solution to this? I'd like to keep my database as clean as possible.. Looking trough the code of redmineup_tags I maybe can just remove the `taggings` and `tags` table? Or better not because it's introduced/used by redmineup_crm plugin? Maybe there's a way to clean up the data by removing all data from `taggings` table which has the `taggable_type` set to `Issue`?

**Comment by alexandermeindl** [comment]
You cannot use uninstall from [redmineup_tags](https://www.redmine.org/plugins/redmineup_tags) plugin.

You have to choices:

1) uninstall redmineup_tags plugin before installing additional_tags and loose all your existing tags.
2) do it as described here: https://github.com/AlphaNodes/additional_tags#migrate-from-other-plugin - you cannot use uninstall procedure from old plugin - if you really want to drop tables from old plugin, you have to remove it manually. But if you uninstall additional_tags and want to reuse redmineup_tags, you get problems with database migration (if tables have been dropped)
