### ISSUE TITLE
not working in 5.0.3 ruby 3.1.2

### ISSUE THREAD

**Issue by ashrafalzyoud** [AlphaNodes/additional_tags#31]
```
ActionView::Template::Error (Array::ArrayRowIsNotAHash):
     9:                             title: "#{l :button_check_all}/#{l :button_uncheck_all}"
    10: 
    11:           th = l :field_name
    12:           - manageable_tag_columns.each do |_column, column_values|
    13:             th = column_values[:label]
    14:           th
    15:       tbody
  
plugins/additional_tags/lib/additional_tags/tags.rb:28:in `available_tags'
plugins/additional_tags/lib/additional_tags/patches/issue_patch.rb:41:in `available_tags'
plugins/additional_tags/app/helpers/additional_tags_helper.rb:18:in `manageable_tag_columns'
plugins/additional_tags/app/views/additional_tags/settings/_manage_tags.html.slim:12
app/views/common/_tabs.html.erb:21
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20
app/helpers/application_helper.rb:497:in `render_tabs'
plugins/additional_tags/app/views/additional_tags/settings/_settings.html.slim:9
app/views/settings/plugin.html.erb:6
app/views/settings/plugin.html.erb:4
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by alexandermeindl** [comment]
Hi @ashrafalzyoud,

I cannot reproduce this error. Redmine 5.0.3 with ruby 3.1.2 works without problems. Which other plugins do you use?

**Comment by alexandermeindl** [comment]
Because of no response I close this issue.
